notifier:
  platforms:
    youtube:
      enabled: yes
      downloader: ytarchive # optional field, will default to yt-dlp, can be set to either 'yt-dlp', 'yt-dlp/piped' or 'ytarchive'
      restream_priority: 1 # optional field, sets the platform priority (ignore if there's already a stream going from a higher priority platform)
      google_credentials: client_secret.json # mandatory field, google credentials file with enabled YouTube Data API
      channel: UCSJ4gkVC6NrvII8umztf0Ow # mandatory field, YouTube channel ID
      scraper_refresh: 5 # scraper livestream check time in minutes, set to 0 to disable
      api_refresh: 0 # API livestream check time in minutes, set to 0 to disable
      healthcheck: https://hc-ping.com/your-uuid-here # healthcheck URL
    rumble:
      enabled: yes
      downloader: yt-dlp # optional field, only yt-dlp supported for now
      restream_priority: 3 # optional field, sets the platform priority (ignore if there's already a stream going from a higher priority platform)
      channel: Destiny # mandatory field, Rumble channel ID
      scraper_refresh: 5 # scraper livestream check time in minutes
      healthcheck: https://hc-ping.com/your-uuid-here # healthcheck URL
    kick:
      enabled: yes
      downloader: N_m3u8DL-RE # optional field, will default to yt-dlp, can be set to either 'yt-dlp' or 'N_m3u8DL-RE'
      restream_priority: 2 # optional field, sets the platform priority (ignore if there's already a stream going from a higher priority platform)
      channel: destiny # mandatory field, Kick channel ID
      scraper_refresh: 5 # scraper livestream check time in minutes
      healthcheck: https://hc-ping.com/your-uuid-here # healthcheck URL
  plugins:
    enabled: no
    path: ./notifier.lua # path to the lua plugin
  verbose: no # increases log verbosity